attributes:
  nfs_volume_path:
    value: ''
    label: 'NFS volume path:'
    description: 'e.g. 192.168.0.2:/nfs/vol'
    weight: 10
    type: "text"
  nfs_mount_point:
    value: ''
    label: 'NFS mount point on Controller:'
    description: 'e.g. /mnt/nfs/vol'
    weight: 20
    type: 'text'

