attributes:
  nfs_volume_path:
    value: '/nfs'
    label: 'Shared folder on NFS Server:'
    description: 'e.g. /nfs/vol'
    weight: 10
    type: "text"
    regex:
      source: '.+'
      error: "This field should not be empty"
  nfs_mount_point:
    value: '/mnt/nfs'
    label: 'Cinder mount point base folder:'
    description: 'e.g. /mnt/nfs'
    weight: 20
    type: 'text'
    regex:
      source: '.+'
      error: "This field should not be empty"
  nfs_net_mask:
    value: '255.255.255.0'
    label: 'NFS Network Mask:'
    description: 'e.g. 255.255.255.0'
    weight: 30
    type: 'text'
    regex:
      source: '.+'
      error: "This field should not be empty"

